### ISSUE TITLE
ImportError: cannot import name 'logicle_c'

### ISSUE THREAD

**Issue by aromanillos** [whitews/FlowUtils#3]
i tried to import flowkit but there is an error like:

ImportError: cannot import name 'logicle_c' ithink it is coming from 

\flowutils\transforms.py", line 7, in <module>
    from flowutils import logicle_c

Did it happen before? not sure where it can come from

**Comment by whitews** [comment]
Hi, just seeing this now. What OS are you using? Do you have a C compiler? If so, which one and what version? Looks like the logicle C extension wasn't compiled.

**Comment by aromanillos** [comment]
Hello, sorry for the late answer; I ndeed i did not have the c compiler, i downloaded Visual studio for Windows10 ( version 19 i think) but it is still giving errors

[logflowutils.txt](https://github.com/whitews/FlowUtils/files/3658469/logflowutils.txt)

**Comment by whitews** [comment]
I think this is related to #2 which was recently fixed but not verified, so not PyPI wasn't updated. Can you clone the FlowUtils repository and install using the setup.py, and they retrying the pip install of FlowKit?

**Comment by whitews** [comment]
Updated PyPI with this fix (v0.7.1)
